### ISSUE TITLE
OVA links are broken

### ISSUE THREAD

**Issue by JeGoi** [SpeciesFileGroup/install_taxonworks#11]
OVA links are broken in [VM readme file](https://github.com/SpeciesFileGroup/install_taxonworks/blob/master/development/vm/README.md)
Perhaps due to "more or less deprecated for the Docker approach, but still maintained"

**Comment by mjy** [comment]
Fixed, thanks for the catch @JeGoi.

**Comment by JeGoi** [comment]
@mjy Thank you

**Comment by JeGoi** [comment]
@mjy Could you add the md5sum or shaXXXsum just to check if not corrupted.
Thank you
