### ISSUE TITLE
E: Unable to locate package postgresql-client-10 on docker-compose build

### ISSUE THREAD

**Issue by jhpoelen** [SpeciesFileGroup/install_taxonworks#17]
when running ```sudo docker-compose build``` on ubuntu 18.04 with docker v17.12.1-ce, the following error message is found:

```
Reading state information...
E: Unable to locate package postgresql-client-10
ERROR: Service 'app' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y locales                        postgresql-client-10                        git gcc build-essential                        libffi-dev libgdbm-dev libncurses5-dev libreadline-dev libssl-dev libyaml-dev zlib1g-dev libcurl4-openssl-dev                        pkg-config imagemagick libmagickcore-dev libmagickwand-dev                        libpq-dev libproj-dev libgeos-dev libgeos++-dev                        tesseract-ocr                        cmake                        nodejs yarn &&                        apt clean &&                        rm -rf /var/lip/abpt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
```

**Comment by mjy** [comment]
You shouldn't need sudo, but that's likely not the problem.

**Comment by jhpoelen** [comment]
Good point about sudo, I should probably change the way I configure docker. Regarding the actual issue - am trying to see whether upgrading to 18.04 fixes it.

**Comment by mjy** [comment]
I've replicated the problem on Mac.

**Comment by jhpoelen** [comment]
Did you every consider running all this in travis every week or so?

**Comment by jhpoelen** [comment]
That should catch variability introduced by ```apt update```

**Comment by mjy** [comment]
We have definitely wanted to get the CI/CD pipeline rolling, just been a matter of getting it setup.

**Comment by jhpoelen** [comment]
I can do that now, it think it'll save time in fixing this issue. Perhaps easier if you add me as a contributor. Alternatively, I can do the pull request method and you'll have to manually enable travis / merge pull requests. Let me know what you prefer.

**Comment by mjy** [comment]
Added you here.  Pushed fix.

**Comment by mjy** [comment]
We *just* did a major branch merge hours ago.  Expect other bumpiness.  I see Ruby in dockerfile needs to be bumped as well.

**Comment by jhpoelen** [comment]
Ok, fastening my seatbelt ; )

**Comment by mjy** [comment]
Still an issue with getting right Ruby version.  Back at it ASAP but off for a bit.

**Comment by mjy** [comment]
`docker-compose build` working on mac/ubuntu 16.04

**Comment by jhpoelen** [comment]
looks like travis has similar results. Closing issue.
