### ISSUE TITLE
intermittent network bridge failures when running docker-compose build

### ISSUE THREAD

**Issue by jhpoelen** [SpeciesFileGroup/install_taxonworks#18]
In the couple of times I've attempted to get ```docker-compose build``` to run, I am noticing intermittent network bridge failures. Re-running the build process usually fixes the issue after a couple of tries. 

Error messages look like:

```
ERROR: Service 'app' failed to build: failed to create endpoint fervent_varahamihira on network bridge: network ec470f35613f970aa5133a5d9acb5e12425bc81e23df1a34b7ff6a81cf663d45 does not exist
```

**Comment by jhpoelen** [comment]
Possibly related to https://github.com/moby/moby/issues/15341#issuecomment-218930712 .

**Comment by jhpoelen** [comment]
/Note that using approach outlines here: https://github.com/SpeciesFileGroup/install_taxonworks/issues/19#issuecomment-427951316 , the errors no longer occur.

**Comment by LocoDelAssembly** [comment]
@jhpoelen guess we are good now?
