### ISSUE TITLE
Install problem: Error 9/11 RUN bundle install -j1

### ISSUE THREAD

**Issue by dominicev** [SpeciesFileGroup/install_taxonworks#35]
Installing on Windows 11.

On the steps

```
docker-compose build --pull
docker-compose up
```

I get the output errors below.

`=> ERROR [ 9/11] RUN bundle install -j1                                                                          33.5s
------CHED [ 4/11] ADD package-lock.json /app/                                                                     0.0s
 > [ 9/11] RUN bundle install -j1:on /app/                                                                         0.0s
#0 0.424 Don't run Bundler as root. Installing your bundle as root will break this                                 0.0s
#0 0.424 application for all non-root users on this machine.                                                       0.0s
#0 0.424 Bundler 2.4.7 is running, but your lockfile was generated with 2.3.24. Installing Bundler 2.3.24 and restarting using that version.N bundle install -j1                                                                          33.5s
#0 2.483 Fetching gem metadata from https://rubygems.org/.
#0 2.522 Fetching bundler 2.3.24
#0 2.659 Installing bundler 2.3.24
#0 2.797 Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
#0 2.797 installing your bundle as root will break this application for all non-root
#0 2.797 users on this machine.
#0 3.212 Fetching gem metadata from https://rubygems.org/........
#0 5.099 Fetching https://github.com/LocoDelAssembly/gpx.git
#0 5.813 Fetching https://github.com/LocoDelAssembly/paperclip.git
#0 7.895 Fetching https://github.com/LocoDelAssembly/serrano.git
#0 8.576 Fetching https://github.com/mmotherwell/best_in_place
#0 9.160 Fetching https://github.com/mjy/rqrcode.git
#0 9.639 Fetching https://github.com/LocoDelAssembly/dwc-archive.git
#0 10.40 Fetching https://github.com/GlobalNamesArchitecture/biodiversity.git
#0 33.41 Your bundle is locked to ruby-prof (1.6.0) from rubygems repository
#0 33.41 https://rubygems.org/ or installed locally, but that version can no longer be
#0 33.41 found in that source. That means the author of ruby-prof (1.6.0) has removed it.
#0 33.41 You'll need to update your bundle to a version other than ruby-prof (1.6.0) that
#0 33.41 hasn't been removed in order to install.
------
[+] Building 37.6s (5/15)
 => [internal] load build definition from Dockerfile.development                                                   0.0s
 => => transferring dockerfile: 44B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for docker.io/sfgrp/taxonworks-base:latest                                            3.2s
 => [internal] load build context                                                                                  0.7s
 => => transferring context: 571.60kB                                                                              0.6s
 => [ 1/11] FROM docker.io/sfgrp/taxonworks-base:latest@sha256:0c73e3579b76aea1512bfc37fa162f5aa25358b4c95ff9748a  0.0s
failed to solve: executor failed running [/bin/sh -c bundle install -j$BUNDLER_WORKERS]: exit code: 7`

I also tried 

`docker-compose down`

and then repeating but it gives the same error.

**Comment by mjy** [comment]
@dominicev Thanks. We're in the process of updating our containers in various ways as I type, which would be a massive co-inicidence, but it appears related (we just handled this problem locally).  Stay tuned.

**Comment by LocoDelAssembly** [comment]
@dominicev can you `git pull` and try again? (make sure you are in `development` branch)

Thanks

**Comment by dominicev** [comment]
It worked now. Thank you!
