### ISSUE TITLE
The PATH in docker need to be edit?

### ISSUE THREAD

**Issue by curiosusJR** [SpeciesFileGroup/install_taxonworks#36]
I had followed guides <https://github.com/SpeciesFileGroup/install_taxonworks/blob/master/development/docker/README.md> and <https://github.com/SpeciesFileGroup/taxonworks_doc/blob/archive/development/HOW-TO.md#create-a-user-from-the-console>. When I try to enter the Rails console, I get errors:
> root@be7db6ceb3d9:/app# rails c
> bash: rails: command not found

I can find `rails` in `GEM_PATH`, so I try to run the command with absolute path and I get:
> /usr/bin/env: ‘ruby_executable_hooks’: No such file or directory

So I add the `GEM_PATH` into `PATH` by editing `/root/.bashrc` and everything runs fine.

**Comment by LocoDelAssembly** [comment]
Have you tried `bundle exec rails c`?

**Comment by curiosusJR** [comment]
> Have you tried `bundle exec rails c`?

@LocoDelAssembly 

Thanks for your reply!
After entering the app shell, running `bundle exec rails c` will get:
> root@be7db6ceb3d9:/app# bundle exec rails c
> Loading development environment (Rails 6.1.7.3)
> irb: warn: can't alias context from irb_context.
> irb(main):001:0>

Is that cool?

**Comment by LocoDelAssembly** [comment]
@curiosusJR yes, that is how you start up the rails console in the docker container. Any rails invocation needs to be prefixed with `bundle exec`.

**Comment by curiosusJR** [comment]
@LocoDelAssembly 
Thank you so much!
