### ISSUE TITLE
Postgres compatibility issues

### ISSUE THREAD

**Issue by daisieh** [SpeciesFileGroup/install_taxonworks#7]
This happened to me and Fauzi thought I should warn people: if your local version of Postgres is 9.6+, you'll have problems with pg_restore for a particular configuration parameter that was introduced in 9.6. Rails and Ubuntu still use 9.5, so what you'll want to do is run not the latest version of pg_restore, but `/Applications/Postgres.app/Contents/Versions/9.5/bin/pg_restore`.

**Comment by LocoDelAssembly** [comment]
Could you be more specific about the problems you had with 9.6+ and the configuration parameter you mention?

**Comment by daisieh** [comment]
This exact problem: https://github.com/PostgresApp/PostgresApp/issues/382 but with pg_restore. Fauzi dumped his db from his Ubuntu machine and I wanted to load it into my Docker (both 9.5), but those are both 9.5, and when I ran the 9.6 pg_restore from my local machine, I got the extra configuration parameter.

**Comment by daisieh** [comment]
I don't think that there's anything that needs to be changed exactly, just maybe make a note in the instructions?

**Comment by Dschoni** [comment]
Just for reference: The missing parameter is "idle_in_transaction_session_timeout", but at leas for me, this is an error, that can be safely ignored.
