### ISSUE TITLE
Clean install on mac (High Sierra) ImageMagick problem

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/install_taxonworks#9]
Starting with a clean install of High Sierra, I was building a new TaxonWorks installation, and discovered that the rmagick gem would not install, because it could not find the ImageMagick installation, probably because, rather than `/usr/local/Cellar/imagemagick/`, it got installed in `/usr/local/Cellar/imagemagick@6`. In order to facilitate the install of the rmagick gem, I added `PKG_CONFIG_PATH=` invocation  (see `macos.md`). This permitted the rmagick gem install to succeed, but many of the image-related tests fail. Since this machine was needed to run a specific rake task, and image processing was not required, I left it as it was. As I understand it, the default ImageMagick is at version 7+, which has not been shown to work with the rmagick gem (per MJY), thus the installation of imagemagick@6.

**Comment by mjy** [comment]
Closing this.  Add pertinent bits to a troubleshooting section if needed.
